id: P8269805E
initial_creation_type: input
source_metadata:
  title: Aspiration Prayers
  language: en
  description: 'A series of prayers of aspiration (Skt. praṇidhāna; Tib. smon lam)
    and works from related genres, including prayers for the spread of the teachings
    (bstan rgyas smon lam):'
  volume:
    2431c811280649a4aabadee2e96f10c1:
      title: 'Fostering Recollection to Dispel the Torment of Deluded Perception:
        An Aspiration for the Bardos'
      parent: Bardos
    5ece9afa7ac8465cac459d5562397e4f:
      title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
      parent: Bardos
    8c972206a7764fa8b372e0f8824bbd87:
      title: Maitreya's Aspiration
      parent: Bodhisattva Aspirations
    959df8fe17144b909612f2e4986dd425:
      title: 'The Blissful Path to the Ocean of Bodhichitta: A Brief Prayer of Aspiration
        for Mind Training'
      parent: Bodhisattva Aspirations
    ffe62c6096474affa4d39585430cea87:
      title: 'The Excellent Path to Enlightenment: An Aspiration Towards the Mahāyāna
        Mind Training'
      parent: Bodhisattva Aspirations
    da2d67665efd45c49ec2d6fb8eaba93e:
      title: 'The Heart of the Mahāyāna Path: A Bodhisattva’s Prayer of Aspiration'
      parent: Bodhisattva Aspirations
    62a4836af8d34583be8ec7475c392f62:
      title: 'The Finest Jewel: An Aspiration Prayer of Mahāyāna Mind Training'
      parent: Bodhisattva Aspirations
    99c874e23a2746f3b9723f254b060cd4:
      title: Prayer of Aspiration Incorporating the Eight Thoughts of Great Beings
        Who Follow the Way of the Mahāyāna
      parent: Bodhisattva Aspirations
    d636344a6ca1489e88522abf866d39b7:
      title: Bodhicitta Aspiration
      parent: Bodhisattva Aspirations
    79fd1fa6281448e38197bd9f0e9ad67d:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Bodhisattva Aspirations
    50a0849bf76443158cc55eee2c0771c7:
      title: The Way to Explain the King of All Aspiration Prayers, the Secret Vajra
        Knot
      parent: Commentaries
    0bdc0d7186b14a30b125fe874f19a867:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Copper-Coloured Mountain
    9308930821b34a65a28a90e1c6db0942:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Copper-Coloured Mountain
    06d7511ba78f4dd3836907fb9450235d:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Copper-Coloured Mountain
    b4ee0b8806b84afa9dcce337ca81d4f9:
      title: A Prayer of Aspiration for the Mountain of Glory
      parent: Copper-Coloured Mountain
    5a66cf0cd21a4a438461dcea1f50972b:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Copper-Coloured Mountain
    b3e48d50a6ac4e348fd1c696f5041b8d:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Copper-Coloured Mountain
    fd2e8bbf292e40f0852714f740f58021:
      title: 'The Song of Devotion: Verses of Aspiration for the Fulfilment of the
        Enlightened Vision of Khenchen Jigme Phuntsok, the Reincarnation of Terton
        Lerab Lingpa'
      parent: Devotion
    eadb31d0f0cb48dfba43c10202c33b1c:
      title: An Aspiration
      parent: Dzogchen
    0250b3bb0e494724ae5f05ade9f63ecc:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Dzogchen
    095007f032d64f8e9a4628130b64060e:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Dzogchen
    cc4bee1bce4e49c18745ec863acf6ba7:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Dzogchen
    cc81f7a940c446c5aa98c4e087c275f0:
      title: Prayer of the View, Meditation and Conduct
      parent: Dzogchen
    1c96c454d0ba4373932e607a6c3cda15:
      title: Profound Prayer of Aspiration
      parent: Dzogchen
    003e48cff00841f78cb4cdbb3f1f88a5:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: General
    40b4ecf292b14ec7b03558ce7dceed36:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: General
    c0f85df087f545b0bbadab18f91907c5:
      title: 'The Vidyādharas'' Words of Truth: An Aspiration Connected with the Stages
        of the Path of the Three Roots, from the Heart Essence of the Vast Expanse'
      parent: General
    9d2ca7ec50964adebaf92d9520652e65:
      title: 'Wisdom''s Melody: An Aspiration to Realize Madhyamaka, Mahāmudrā, and
        Mahā Ati'
      parent: General
    7d2aa36163d044af968ccbdcf280f8d9:
      title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī'
      parent: General
    c8f6777dd41c45a1b8e624a609fa838c:
      title: Aspirations in Accordance with the Dharma
      parent: General
    95d2b1525f554b5d8ad07b930fbf1509:
      title: Aspiration at the Moment of Death
      parent: General
    4f2a05ef527442018e5a8090e1c535b0:
      title: Aspiration Prayer of the Ultimate Definitive Meaning
      parent: General
    8d65157ff22540f8871ff29f28be1e34:
      title: An Aspiration Prayer
      parent: General
    31544b36d5c1443a85528f592da61a5e:
      title: Aspiration for All Lives to Come
      parent: General
    28fc12d3340749d9b831df0272f66032:
      title: Aspiration Written in Sadness During the Water Snake Year
      parent: General
    9d1b998148af4db1a0be411886f3748a:
      title: Aspiration Written on the Occasion of Princess Sangdé’s Passing in Sikkim
      parent: General
    6e70de6680e8446eaafca129d6988137:
      title: Aspiration to Accomplish Every Aim
      parent: General
    2aff941f532f40449226c590fd96a6d1:
      title: Aspiration to Be Reborn at the Vajra Seat (Bodhgayā), Akaniṣṭha on Earth
      parent: General
    827505af307a49718345834d0e1035f3:
      title: Prayer of Aspiration
      parent: General
    78a15a8b0f04430491ebf855437cdbb1:
      title: 'The Jewelled Rosary: An Aspiration Toward Longed-for Aims'
      parent: General
    ab8d95321f3143e2822ca53d56ca6d30:
      title: 'The Swift Fulfilment of Wishes: A Prayer of Aspiration'
      parent: General
    e687cc9b7dde4afb8876225ea9bf2a28:
      title: An Aspiration for the Final Age
      parent: General
    cf8fb6448d1c44b79ce507fc0e3d74ff:
      title: 'Entering the City of Omniscience: An Aspiration Prayer for Actualizing
        Words of Truth'
      parent: General
    c1a475ea766d43fdb6fdf1ed3cab698e:
      title: Aspiration for Future Lives
      parent: General
    b81f06a08a4f4b43a8e8576969415fbb:
      title: Aspiration to be Cared For in Every Lifetime
      parent: General
    c2a4e1ef804345739ad0c61afcc6eb83:
      title: 'The Sun of Samantabhadra’s Realm: The Quintessence of Oceanic Prayers
        of Aspiration'
      parent: General
    29c20dd5d52345b79481c9a9064f757b:
      title: An Aspiration to Travel to the Hidden Land of Pemokö
      parent: General
    014c6ca92a5c4281b4e9200932a03935:
      title: 'The Magical Lasso: A Prayer of Aspiration to Accomplish Khecara'
      parent: General
    b6e23cfc2321490c87c4054317bfe127:
      title: The Secret Vajra Knot
      parent: General
    ed40a0649a444603a0708b24717f829d:
      title: Aspiration for the Four Activities
      parent: General
    be8ae9b2ce0945a0a4093598189808a1:
      title: The Source of Beings' Happiness
      parent: General
    10194cd343e4449d9e456a995167782e:
      title: The Thirty Aspirations
      parent: General
    cb7752a0a5864aa497506371eade54ae:
      title: Yeshe Tsogyal's Prayer
      parent: General
    6958c3e1a5364261a3a2db3034f60dba:
      title: Aspiration Prayer from Tārā Sādhana
      parent: General
    e4a98f0406df4632b1bb642239a27d3a:
      title: Verses of Aspiration to Recite While Prostrating
      parent: General
    e5c0ba0b3f644f61a90623d4833daf99:
      title: A Prayer of Aspiration
      parent: General
    b9ff9afc72564b4f90adbf0d2b38d50b:
      title: Aspiration Prayer
      parent: General
    023d05655bc444a0bfa4b6bb57fe117f:
      title: Aspiration for the Stages of the Path
      parent: Lamrim
    a0f51e74fd5b4ff48fab214b9cde909c:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: Longevity
    73119acd20884b4890660f893a2626e3:
      title: Concise Middle Way Aspiration
      parent: Madhyamaka
    050f9dab3126452f8af2a49dd14b71bb:
      title: Middle Way Aspiration
      parent: Madhyamaka
    d5ef792983114821b142ae67ff957cae:
      title: Aspiration of the Mahāmudrā of Definitive Meaning
      parent: Mahāmudrā
    4dd89ef915d04dd08f31204ae3562a7a:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Peace and Welfare
    72f1a0191c5346a8b31f5f114edac206:
      title: Aspiration for the Country’s Welfare
      parent: Peace and Welfare
    9788d6586c054c26884a479367183bf4:
      title: The Prayer of the Words of Truth
      parent: Peace and Welfare
    51e426f1d3f740768022ba56cd410cc8:
      title: 'The Resounding Drum of Truth: A Prayer and Aspiration'
      parent: Peace and Welfare
    237a22f7628b41e79e8267e9e02a6cf4:
      title: Prayer for Peace and Stability in Tibet
      parent: Peace and Welfare
    4702d917f9af401cb03fb4f3f5734079:
      title: 'Burgeoning Joy and Happiness: An Aspiration for the Welfare of the Great
        Hidden Land of Sikkim'
      parent: Peace and Welfare
    c6af4077500c49e5a9b9f3d16d7af408:
      title: 'Declaration of the Power of Truth: A Prayer to Overcome Invading Forces'
      parent: Peace and Welfare
    f5011c1b5c3b4e6ea00bffa9399dafc1:
      title: 'The Fulfilment of All Aims and Wishes: An Aspiration to Request the
        Safeguarding of Happiness in Tibet'
      parent: Peace and Welfare
    d4b9b7aa61ba49e4bbd297dd31d7ca15:
      title: Prayer for Dispelling Famine
      parent: Peace and Welfare
    1df3ff60073f4ca19a5cb3e36e8a3695:
      title: Prayer of Truthful Words to Pacify the Fear of War
      parent: Peace and Welfare
    d93e7dd1e227423ba4536166818fcfe0:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Peace and Welfare
    00c6da0779ac472cb122f9bf1a296255:
      title: 'The Jewelled Garland: An Aspiration for the Spread of the Teachings
        of the Omniscient Father and Son, Masters of the Teachings of the Ancient
        Translations'
      parent: Prayers for the Spread of the Teachings
    f506b59c4f624a8396a4a00e3d50379c:
      title: Prayer for the Future of the Dharma
      parent: Prayers for the Spread of the Teachings
    85a1b0871a3e48928275e0b86ac04fa7:
      title: Aspiration Prayer for the Flourishing of the Jonang Teachings
      parent: Prayers for the Spread of the Teachings
    d458f433b2484e16b531c33c2d593012:
      title: 'The Sage''s Harmonious Song of Truth: A Prayer for the Flourishing of
        the Non-Sectarian Teachings of the Buddha'
      parent: Prayers for the Spread of the Teachings
    68bb10cbaf7b4af38c8077062ac8355f:
      title: 'All-Pervading Auspiciousness: An Aspiration for the Spread of the Teachings
        of the Eight Great Chariots of the Practice Lineage'
      parent: Prayers for the Spread of the Teachings
    d12a99fcf6594aef8e28a91125912832:
      title: Aspiration for the Spread of the Guhyagarbha Teachings
      parent: Prayers for the Spread of the Teachings
    4706c6235107413083f5cac385628902:
      title: Aspiration for the Spread of the Teachings
      parent: Prayers for the Spread of the Teachings
    d3dbe8a2197e4c30afa9e16eed812aab:
      title: 'Blazing Splendour of Good Fortune: A Prayer for the Spread of the Teachings
        of the Katok Tradition'
      parent: Prayers for the Spread of the Teachings
    ba2c21921c1d4af993a30c9299380792:
      title: 'Introduction to the Buddha’s Words: A Praise and Aspiration Related
        to the Words of the Victorious One'
      parent: Prayers for the Spread of the Teachings
    9bd2c7644963482ab9ae6287bb5dc0d1:
      title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the
        Omniscient Buddha''s Teachings'
      parent: Prayers for the Spread of the Teachings
    19f5bb141631463b8af65af0173883ec:
      title: The Last Testament of Katok Dampa Deshek
      parent: Prayers for the Spread of the Teachings
    e98e0d6e4bcc43aaab676ed5b5ca1434:
      title: Prayer of Aspiration for the Buddhist Teachings to Flourish in Taiwan
      parent: Prayers for the Spread of the Teachings
    33b9f68ef3ff4722bca97de62965d009:
      title: Aspiration for the Spread of the Teachings of the Eight Chariots of the
        Practice Lineage
      parent: Prayers for the Spread of the Teachings
    c0f3307f37ce4faaacd8e54d9422df2c:
      title: Clouds of Offerings to Delight the Victorious Ones – An Aspiration Prayer
        for the Spread of the Teachings of the Lord of Siddhas, Dzogchen Rinpoche
      parent: Prayers for the Spread of the Teachings
    90f1b3e7cab843d0aa79524b87c23525:
      title: 'Words of Truth: An Aspiration for the Spread of the Noble Gendenpa Tradition'
      parent: Prayers for the Spread of the Teachings
    a21daf74fe9c43c3ab522f1c779acb8c:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Prayers for the Spread of the Teachings
    8f293679650a4e92957c149700de0ac9:
      title: Prayer for the Flourishing of the Teachings
      parent: Prayers for the Spread of the Teachings
    74b8ef07ccca491f986860b71bd8eb65:
      title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
      parent: Prayers for the Spread of the Teachings
    48a6498579cf4c8bb286f32785e34a41:
      title: Prayer for the Flourishing of the Dzogchen Teachings of Sogyal Rinpoche,
        the incarnation of Lerab Lingpa
      parent: Prayers for the Spread of the Teachings
    397e99de31c54462973e74b2d6b33948:
      title: A Brief Method for Reciting Samantabhadra's Prayer of Good Actions
      parent: Recitation Guides
    768f3bfb9c3b4b13bdd2bba516f49044:
      title: A Prayer for Translators
      parent: Translation
    b1865e4a4e3144a4b1370d8c6bc9d92a:
      title: An Aspirational Prayer to Behold the Beautiful Face of Khecharī
      parent: Vajrayoginī
created_at: '2022-03-01T02:50:17.914620'
last_modified_at: '2022-03-01T02:50:17.914629'
